### ISSUE TITLE
Any plans to add an image widget?

### ISSUE THREAD

**Issue by jchappelle** [SkyAphid/Clear#1]
Hi I was wondering if you plan on adding an image widget?

**Comment by SkyAphid** [comment]
Heya! I'm not developing this system anymore, but the code is heavily documented and has all of the tools to make one yourself. It's based on NanoVG and is simply a system that organizes it into an easy to use framework, so if you look up the documentation for NanoVG, it's easy to extend Clear to include that functionality.

**Comment by jchappelle** [comment]
Ok. Thanks so much for the reply!
